# -*- mode: ruby -*-
# vi: set ft=ruby :

# https://docs.vagrantup.com.

Vagrant.configure(2) do |config|

    config.vm.define "client" do |client|
        client.vm.box = "ubuntu/trusty64"
        client.vm.hostname = "client"
        client.vm.network "private_network", type: "dhcp"

        client.vm.provision :shell, path: "scripts/provision.sh"

        client.vm.provision :shell, inline: "su - vagrant -c /vagrant/scripts/install_aspera.sh"
        client.vm.provision :shell, path: "./scripts/install_gridftp_ubuntu.sh"
    end

    config.vm.define "server" do |server|
        server.vm.box = "ubuntu/trusty64"
        server.vm.hostname = "server"
        server.vm.network "private_network", type: "dhcp"

        server.vm.provision :shell, path: "./scripts/install_gridftp_ubuntu.sh"
    end
end
