# -*- mode: ruby -*-
# vi: set ft=ruby :

# https://docs.vagrantup.com.

Vagrant.configure(2) do |config|

    config.vm.box = "ubuntu/trusty64"

    config.vm.provision :shell, path: "scripts/provision.sh"

    config.vm.provision :shell, inline: "su - vagrant -c /vagrant/scripts/install_aspera.sh"

end
