#!/bin/bash

SCRIPTS_DIR=$( cd $(dirname $0); pwd -P )

flake8 \
    --exclude="${SCRIPTS_DIR}/../client/build/" \
    --max-line-length=10000 \
    "${SCRIPTS_DIR}/../client" \
    "${SCRIPTS_DIR}/../metadata_repository"
