#!/usr/bin/env python3

import os
import sys


project_dir = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
sys.path.insert(0, project_dir)


from app.models import db_engine, BaseModel
BaseModel.metadata.create_all(bind=db_engine)
