#!/usr/bin/env bash

# Provision Ubuntu 16.04 server for metadata repository

set -e

apt-get update

# ======================================================
# PostgreSQL
# ======================================================

apt-get install --assume-yes postgresql postgresql-contrib

PG_VERSION=$(psql --version | awk '{ print $3 }' | awk 'BEGIN { FS="." } ; { print $1"."$2 }')
PG_CONF="/etc/postgresql/$PG_VERSION/main/postgresql.conf"
PG_HBA="/etc/postgresql/$PG_VERSION/main/pg_hba.conf"

# Enable password authentication for bdss database user
sed -i '/local   all             postgres                                peer/i \
local   bdss            bdss                                    md5' "$PG_HBA"

echo "client_encoding = utf8" >> "$PG_CONF"

service postgresql restart

# Create database and user
DB_NAME=bdss
DB_USER=bdss
DB_PASS=bdss

cat << EOF | su - postgres -c psql
-- Create the database user:
CREATE USER $DB_USER WITH PASSWORD '$DB_PASS';

-- Create the database:
CREATE DATABASE $DB_NAME WITH OWNER=$DB_USER
                                 LC_COLLATE='en_US.utf8'
                                 LC_CTYPE='en_US.utf8'
                                 ENCODING='UTF8'
                                 TEMPLATE=template0;
EOF

# ======================================================
# Python
# ======================================================

apt-get install --assume-yes python3-dev libffi-dev python3-pip
pip3 install --upgrade pip

# ======================================================
# Apache
# ======================================================

apt-get install --assume-yes apache2 apache2-dev

# Install mod_wsgi (apt-get repo version is outdated)
pip3 install mod_wsgi
/usr/local/bin/mod_wsgi-express install-module
echo "LoadModule wsgi_module $(/usr/local/bin/mod_wsgi-express module-location)" > /etc/apache2/mods-available/wsgi_express.load
echo "WSGIPythonHome /usr" > /etc/apache2/mods-available/wsgi_express.conf
a2enmod wsgi_express
service apache2 restart

# ======================================================
# BDSS
# ======================================================

pip3 install --requirement /vagrant/requirements.txt

# Configure
cd /vagrant
cat <<EOF > .env
DATABASE_URL=postgresql+psycopg2://bdss:bdss@localhost/bdss
SESSION_KEY=$(python3 ./scripts/generate_flask_key)
EOF

# Create database schema
apt-get install --assume-yes libpq-dev
pip3 install psycopg2
cd /vagrant
sh ./scripts/with_dotenv alembic upgrade head

# Apache configuration for BDSS
PYTHON_VERSION=$(python3 --version 2>&1 | awk '{ print $2 }' | awk -F. '{ print $1"."$2 }')

cat > /etc/apache2/sites-available/bdss.conf <<EOF

# http://docs.vagrantup.com/v2/synced-folders/virtualbox.html
EnableSendfile Off

<VirtualHost *:80>

    <Directory "/vagrant">
        Require all granted
    </Directory>

    Alias /static/ /vagrant/app/static/

    WSGIDaemonProcess bdss user=www-data group=www-data processes=1 threads=5 \\
        python-path=/usr/local/lib/python${PYTHON_VERSION}/dist-packages:/vagrant
    WSGIScriptAlias / /vagrant/app.wsgi
    WSGIProcessGroup bdss
    WSGIApplicationGroup %{GLOBAL}
    WSGIPassAuthorization On

</VirtualHost>
EOF

a2dissite 000-default
a2ensite bdss
service apache2 reload
