#!/bin/bash

# Run migrations using alembic against the database specified by
# DATABASE_URL in metadata_repository/.env

SCRIPTS_DIR=$(cd $(dirname $0); pwd -P)
PROJECT_DIR=$(cd "${SCRIPTS_DIR}/.."; pwd -P)

cd "$PROJECT_DIR"

alembic upgrade head
