#!/usr/bin/env python3

import os
import sys

project_dir = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
sys.path.insert(0, project_dir)

from app import app as application

args = {
    "debug": True,
}

if len(sys.argv) > 1 and sys.argv[1] == "--public":
    args["host"] = "0.0.0.0"

if __name__ == "__main__":
    application.run(**args)
