#!/usr/bin/env python3

import os
import sys


project_dir = os.path.realpath(os.path.join(os.path.dirname(__file__), "../"))
sys.path.insert(0, project_dir)


from app import app as application


if __name__ == "__main__":
    args = dict(debug=True, extra_files=[])

    extra_dirs = [os.path.join(project_dir, "app/templates")]
    for extra_dir in extra_dirs:
        for dirname, _, files in os.walk(extra_dir):
            for filename in files:
                filename = os.path.join(dirname, filename)
                args["extra_files"].append(filename)

    if "--public" in sys.argv[1:]:
        args["host"] = "0.0.0.0"

    application.run(**args)
